version: '3.8'

services:
  bookstack:
    image: ${BOOKSTACK_IMAGE}
    container_name: ${BOOKSTACK_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MAIL_DRIVER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
    volumes:
      - bookstack_data:/config
    depends_on:
      - db
    networks:
      - bookstack_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${BOOKSTACK_HEALTHCHECK_URL} || exit 1"]
      interval: ${BOOKSTACK_HEALTHCHECK_INTERVAL}
      timeout: ${BOOKSTACK_HEALTHCHECK_TIMEOUT}
      retries: ${BOOKSTACK_HEALTHCHECK_RETRIES}
      start_period: ${BOOKSTACK_HEALTHCHECK_START_PERIOD}

  db:
    image: ${DB_IMAGE}
    container_name: bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstack_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_HEALTHCHECK_USER} -p${DB_HEALTHCHECK_PASSWORD}"]
      interval: ${DB_HEALTHCHECK_INTERVAL}
      timeout: ${DB_HEALTHCHECK_TIMEOUT}
      retries: ${DB_HEALTHCHECK_RETRIES}
      start_period: ${DB_HEALTHCHECK_START_PERIOD}

  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:${NGINX_INTERNAL_PORT}"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bookstack
    networks:
      - bookstack_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q ${NGINX_HEALTHCHECK_URL} || exit 1"]
      interval: ${NGINX_HEALTHCHECK_INTERVAL}
      timeout: ${NGINX_HEALTHCHECK_TIMEOUT}
      retries: ${NGINX_HEALTHCHECK_RETRIES}
      start_period: ${NGINX_HEALTHCHECK_START_PERIOD}

volumes:
  bookstack_data:
  db_data:

networks:
  bookstack_net:
    driver: bridge
