name: Deploy BookStack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🔐 Set Vault Secrets as ENV
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          echo "Logging into Vault..."
          vault login $VAULT_TOKEN

          echo "Fetching secrets..."
          vault kv get -format=json secret/bookstack | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"' > .env

          echo "Vault secrets loaded into .env:"
          cat .env

      - name: 🐳 Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: 🧪 Build Secure Docker Image
        run: |
          docker build -t bookstack:secure-latest .

      - name: 📦 Compose Up
        run: |
          docker compose -f docker-compose.yml --env-file .env up -d

      - name: 🧼 Clean Up Dangling Images
        run: docker image prune -f
